let productsDb = [
  {
    id: 1,
    title: "Realme Earpods",
    price: "1000.00 Eg",
    imgUrl: "/images/Earpods.jpg",
    liked: false,
    added: false,
    qty: 0,
  },

  {
    id: 2,
    title: "Flormar EyeLiner",
    price: "200.00 Eg",
    imgUrl: "/images/eyeliner.jpg",
    liked: false,
    added: false,
    qty: 0,
  },
  {
    id: 3,
    title: "Black Gaming Chair",
    price: "2000.00 Eg",
    imgUrl: "/images/gaming chair.jpg",
    liked: false,
    added: false,
    qty: 0,
  },
  {
    id: 4,
    title: "Nuxe White Ultimate ",
    price: "700.00 Eg",
    imgUrl: "/images/nuxe white ultimateglow.webp",
    liked: false,
    added: false,
    qty: 0,
  },
  {
    id: 5,
    title: "Raelme Watch 2",
    price: "2500.00 Eg",
    imgUrl: "/images/real me watch2.jpg",
    liked: false,
    added: false,
    qty: 0,
  },
  {
    id: 6,
    title: "Women Adidas",
    price: "1500.00 Eg",
    imgUrl: "/images/women addidas.jpg",
    liked: false,
    added: false,
    qty: 0,
  },
];
